[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]

[project]
name = "line-todo-bot"
version = "0.1.0"
dependencies = [
    "flask",
    "python-dotenv",
    "line-bot-sdk",
    "sqlalchemy",
    "pg8000",
    "alembic",
    "asgiref",
    "workers-py"
]

[dependency-groups]
dev = [
    "workers-py",
    "workers-runtime-sdk",
]
